### ISSUE TITLE
yii2-webpack-settings problems

### ISSUE THREAD

**Issue by alexstulov** [leonied7/yii2-webpack#1]
Запускаю yii2-webpack -> Заполняю поля -> Получаю yii2-webpack-settings.json с запятой после последней строки, т.е. невалидный json. Из-за этого конфиг не применяется и я получаю дефолтные namespace, assetDirectory и т.д. Никаких ошибок при запуске npm run build не получаю.

**Comment by leonied7** [comment]
@alexstulov укажите какими данными заполняете и выходной файл yii2-webpack-settings.json
